name: Update NLRB Map data

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:  

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scripts
      run: |
        python scripts/data_collection.py  
        python scripts/map_generator.py
    
    - name: Commit and push 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "NLRB Map Update $(date)"
          git push
        fi